### PR TITLE
Update README.md header

### PR DESCRIPTION
**Pull request by emil-applause-testuser**

### CODE REVIEW

**Comment by emil-applause-testuser** [comment]
Collaborator/PR author comment

**Comment by emil-applause** [comment]
Doesn't look good.

**Comment by emil-applause** [comment]
approved

**Comment by emil-applause** [comment]
test

**Comment by emil-applause** [comment]
approved

**Comment by emil-applause** [comment]
approved

**Comment by emil-applause** [comment]
approved

**Comment by emil-applause** [comment]
approved

**Comment by emil-applause** [comment]
approved

**Comment by emil-applause** [comment]
approved

**Comment by emil-applause** [comment]
approved

**Comment by emil-applause** [comment]
approved

**Pull request merged**
